name: "Build & Publish Docker Image"

concurrency:
  group: "publish-${{ github.ref }}"
  cancel-in-progress: true

on:
  push: 
    branches:
      - staging
    tags: 
      - '*'
  pull_request:
  workflow_dispatch:

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  S3MGRT_REGISTRY: ${{ secrets.S3MGRT_REGISTRY }}

jobs:
  s3mgrt:
    runs-on: [self-hosted, arc-runner]
    steps:
      - name: Set docker image tag 
        run: |
          if [[ "${{github.ref}}" == refs/pull/* ]]; then
            tag=${GITHUB_REF/\/merge/}
            echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
          else
            echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
          fi

          echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
          echo "SHA=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}')" >> $GITHUB_ENV
          
      - name: Setup go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18' # The Go version to download (if necessary) and use.

      - name: Clone s3migration
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        run: |
          sudo apt-get update -y
          sudo apt-get install ca-certificates curl gnupg lsb-release -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -y
          sudo apt-get install docker-ce docker-ce-cli containerd.io -y
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker context create s3mgrt_buildx
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build s3mgrt
        run: |
          SHORT_SHA=$(echo ${{ env.SHA }} | head -c 8)
          export DOCKER_BUILD="buildx build --platform linux/amd64,linux/arm64 --push"
          export DOCKER_IMAGE="-t ${{ secrets.S3MGRT_REGISTRY }}:${TAG} -t ${{ secrets.S3MGRT_REGISTRY }}:${TAG}-${SHORT_SHA}"
          docker buildx create --driver-opt network=host --use --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use s3mgrt_buildx
          ./docker.local/bin/build.sh
