name: build-s3-migration

concurrency:
  group: "publish-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [ master, staging, sprint*, fix-windows-ci ]
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build-windows
    runs-on: windows-runner
    defaults:
      run:
        shell: msys2 {0}
    strategy:
     matrix:
      sys: [ MINGW64 ]
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}

      - name: Install libraries
        run: |
          echo 'Y'| pacman -S base-devel git gcc make
      
      - name: Install Clang and Go for MINGW64
        run: |
         echo 'y'| pacman -S  mingw-w64-x86_64-clang mingw-w64-x86_64-go zip unzip

      - name: Set environment variables
        run: |
           export GOROOT=/mingw64/lib/go
           export GOPATH=/mingw64
           export PATH=$PATH:$GOROOT/bin
           export PATH=$PATH:/usr/bin/7z

           # use clang as a default compiler for CGO
           go env -w "CC=/mingw64/bin/clang.exe"

      - name: Checkout
        uses: actions/checkout@v4
