name: build-s3-migration

concurrency:
  group: "publish-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [ master, staging, sprint*, fix-windows-ci ]
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build-windows
    runs-on: [self-hosted, windows-runner]
    steps:
      - name: Setup go 1.22
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Branch
        id: get_branch
        shell: powershell
        run: |
          $BRANCH = "${{ github.ref }}".Replace("refs/heads/", "").Replace("/", "-")
          echo "BRANCH=$BRANCH" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo $BRANCH
      
      - name: Set GITHUB_ENV
        shell: powershell
        run: |
          $branch = "${{ github.ref }}"
          if ($branch -eq "refs/heads/master") {
            echo "TAG=v0.0.0-master" | Out-File -FilePath $env:GITHUB_ENV -Append
          } elseif ($branch -eq "refs/heads/dev") {
            echo "TAG=v0.0.0-dev" | Out-File -FilePath $env:GITHUB_ENV -Append
          } elseif ($branch -eq "refs/heads/staging") {
            echo "TAG=v0.0.0-staging" | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            echo "TAG=v0.0.0-$branch" | Out-File -FilePath $env:GITHUB_ENV -Append
          }
      
      - name: Install Dependencies
        shell: powershell
        run: |
          choco install -y make wget unzip docker-cli
      
      - name: Start Docker Service
        shell: powershell
        run: |
          Start-Service docker
          docker version

      - name: Build Project Using Docker
        shell: powershell
        run: |
          docker run --rm -v ${PWD}:/s3mgrt --workdir=/s3mgrt golang:1.22.5 make build

      - name: Install AWS CLI
        if: github.ref == 'refs/heads/staging'
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi"
          Start-Process msiexec.exe -ArgumentList "/i AWSCLIV2.msi /quiet /norestart" -NoNewWindow -Wait

      - name: Set AWS Credentials
        if: github.ref == 'refs/heads/staging'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: us-east-2
      
      - name: Set Box credentials
        run: |
          box-client-id=${{ secrets.BOX_CLIENT_ID }}
          box-client-secret=${{ secrets.BOX_CLIENT_SECRET }}
